### ISSUE TITLE
problem xamarin.android @ face api

### ISSUE THREAD

**Issue by halukmy** [brminnick/FaceOff#29] opened 2016-10-01 10:48 UTC
dll doesnt works properly can you look it

**Comment by brminnick** [comment] 2016-10-01 18:17
@halukmy I confirmed that I am able to run the current master branch of FaceOff on both my Android emulator & physical Android phone. I am building/deploying the app with Xamarin Studio on macOS Sierra using the latest update in the Stable channel.

Can you provide more details about the error you are experiencing:
* Build Environment 
  * Xamarin Studio or Visual Studio
  * Xamarin Studio Environment Information
    * Xamarin Studio --> About --> Show Details
  * Visual Studio Environment Information
    * Xamarin Information
      * Tools --> Options --> Xamarin
    * Visual Studio Information
      * Version of Visual Studio, e.g. 2015, 2013 or 15
      * Help --> About
* Stack Trace
* Application Output logs
* Deployment Output logs

**Comment by halukmy** [comment] 2016-10-01 19:49
@brminnick  can you try on Xamarin.Android project ? face api doesnt run on it :( and if you can run it , can you share dll and source code with me? 

it even runs on console application but when  i try on xamarin android, face api doesnt run friend ,

![image](https://cloud.githubusercontent.com/assets/2916333/19016645/59191340-8829-11e6-9bfb-1dcc3e992016.jpg)
 i will share screen shot

**Comment by halukmy** [comment] 2016-10-01 19:50
as you see @brminnick  it returns null , i also give internet and other requests from app mainfest,

**Comment by brminnick** [comment] 2016-10-01 19:54
@halukmy I am closing this issue, because it is not related to the [FaceOff app](https://github.com/brminnick/FaceOff).

Here is the repo for the Emotion Cognitive Services API. It is open source so you can read through the source code, or open an issue on their repo if you find a bug.
 https://github.com/Microsoft/ProjectOxford-ClientSDK/tree/master/Emotion/Windows/ClientLibrary

**Closed by brminnick** 2016-10-01 19:54 UTC
